openapi: "3.0.0"
info:
  version: 0.1.1
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: 127.0.0.1/5000
paths:
  /predict:
    post:
      summary: Classify a microgreen
      operationId: PredictMicrogreen
      tags:
        - Microgreen
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"



  /save:
    post:
      summary: Upload a microgreen
      operationId: UploadMicrogreen
      tags:
        - Microgreen
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"



  /species:
    get:
      summary: List of all current classes
      operationId: showSpecies
      tags:
        - Microgreen
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /models:
    get:
      summary: List of all current models
      operationId: showModelsList
      tags:
        - Model
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /download:
    get:
      summary: download current model
      operationId: DownloadModel
      tags:
        - Model
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Model"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


components:
  schemas:

    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string

    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"

    ClassProbability:
      type: object
      required:
        - probability
      properties:
        probability:
          type: number
          format: double

    PredictionMatrix:
        type: array
        items:
          $ref: "#/components/schemas/ClassProbability"

    Model:
      type: object
      required:
        - filename
      properties:
        probability:
          type: string
          format: string


    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string